apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx.fullname" . }}-{{ .Values.image_web.name }}-svc
  labels:
    {{- include "awx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8052
      protocol: TCP
      name: http
  selector:
    {{- include "awx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/role: {{ .Values.image_web.name }}
