apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-awx-psgl
  namespace: awx
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.7
    path: /nas/K8S/awx-psgl/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: awx-db-pvc
  labels:
    app: awx
    role: db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: nfs-awx-psgl