# Configure the AWX Web Docker image
image_web:
  registry: docker.io
  repository: ansible/awx_web
  tag: 9.3.0
  pullPolicy: IfNotPresent

# Configure the AWX Task Docker image
image_task:
  registry: docker.io
  repository: ansible/awx_task
  tag: 9.3.0
  pullPolicy: IfNotPresent

## Configure the ingress resource that allows you to access the
## AWX deployment. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
  #  kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: awx.local
    path: /

    ## Set this to true in order to enable TLS on the ingress record
    tls: false

    ## Optionally specify the TLS hosts for the ingress record
    ## Useful when the Ingress controller supports www-redirection
    ## If not specified, the above host name will be used
    # tlsHosts:
    # - www.magento.local
    # - magento.local

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: awx.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: magento.local-tls
  #   key:
  #   certificate: